book_id: "gri_33125016354728"
book_title: "EntwürfeZuStadtUndLandhäusern"
book_projects_path: "/Users/iankonradjohnson/Library/CloudStorage/GoogleDrive-iankonradjohnson@gmail.com/My Drive/base/abacus/BookProjects"