book_id: "radfordsportfoli00radf"
book_title: "RadfordsPortfolioOfDetailsOfBuildingConstruction"
book_projects_path: "/Users/iankonradjohnson/Library/CloudStorage/GoogleDrive-iankonradjohnson@gmail.com/My Drive/base/abacus/BookProjects"
runpod_pod_id: "sht18toagbx7f6"