output_path: /Users/iankonradjohnson/Library/CloudStorage/GoogleDrive-iankonradjohnson@gmail.com/My Drive/base/abacus/BookProjects
downloader_type: batch_archive_tar
input_list: /Users/iankonradjohnson/base/abacus/BookDownloader/lists/archive-pdfs.txt