downloader_type: rara_manifest
manifest_url: https://www.e-rara.ch/i3f/v20/15372571/manifest
output_path: /Users/iankonradjohnson/Documents/Books/AntiquitiesArchitecture_LuigiCanina/1_Egypt/images/raw/rara-2
structure_id: https://www.e-rara.ch/i3f/v20/15372571/range/15372571
