downloader_type: rara_manifest
manifest_url: https://www.e-rara.ch/i3f/v20/1447284/manifest
output_path: /Users/iankonradjohnson/base/abacus/OcrTranslationProjects/FourBooksOnArchitecture/Book_2/1_OCR_Process/1_raw_scans
structure_id: https://www.e-rara.ch/i3f/v20/1447284/range/1447648
