 downloader_type: rara_manifest
 manifest_url: https://www.e-rara.ch/i3f/v20/15430726/manifest
 output_path: /Users/iankonradjohnson/Downloads/2_Greece_Raw_Scans
 structure_id: https://www.e-rara.ch/i3f/v20/15430726/range/15430726